### PR TITLE
Remove dependency on @babel/traverse to fix linting issues

### LINKED ISSUE #270: [3.9.1] Crash related to <Text>
Hey! 👋 

I'm getting `Error: Couldn't find a Program` after upgrading this package from 3.8.1 to 3.9.1.

Bit of a contrived example below, but seems to reliably trigger the issue and was just about the smallest repro I could manage to find. Not able to post the actual code we're using I'm afraid but it's essentially rendering something like: 

> **Total**: 12.34

Seems to be something to do with nested text that has a function defined somewhere inside. In our case there's a reducer for calculating a total. 

Some notes:
 * Using a named fn instead of the arrow fn still crashes - i.e. `arr.reduce(function add(acc, value) { return acc + value }, 0)`
 * Replacing the reducer callback with something else like a string prevents the crash - i.e. `arr.reduce('blah', 0)` (obviously invalid code though)
 * Defining the reducer callback outside of the JSX also prevents the crash - i.e. `const add = (acc, value) => acc + value` and `arr.reduce(add, 0)` <- looks like this is a reasonable workaround for now...

Repro code:
```tsx
const Comp = () => {
    return (
        <Text>
            <Text>Text</Text> {fn(() => {})}
        </Text>
    )
}
```
```
> eslint .


Oops! Something went wrong! :(

ESLint: 7.8.1

Error: Couldn't find a Program
Occurred while linting /Users/REDACTED/REDACTED/REDACTED.tsx:XX
    at Scope.getProgramParent (/Users/REDACTED/REDACTED/node_modules/@babel/traverse/lib/scope/index.js:813:11)
    at Scope.registerBinding (/Users/REDACTED/REDACTED/node_modules/@babel/traverse/lib/scope/index.js:574:25)
    at Scope.crawl (/Users/REDACTED/REDACTED/node_modules/@babel/traverse/lib/scope/index.js:729:14)
    at Scope.init (/Users/REDACTED/REDACTED/node_modules/@babel/traverse/lib/scope/index.js:709:12)
    at NodePath.setScope (/Users/REDACTED/REDACTED/node_modules/@babel/traverse/lib/path/context.js:131:30)
    at NodePath.setContext (/Users/REDACTED/REDACTED/node_modules/@babel/traverse/lib/path/context.js:147:8)
    at NodePath.pushContext (/Users/REDACTED/REDACTED/node_modules/@babel/traverse/lib/path/context.js:213:8)
    at TraversalContext.visitQueue (/Users/REDACTED/REDACTED/node_modules/@babel/traverse/lib/context.js:100:14)
    at TraversalContext.visitMultiple (/Users/REDACTED/REDACTED/node_modules/@babel/traverse/lib/context.js:79:17)
    at TraversalContext.visit (/Users/REDACTED/REDACTED/node_modules/@babel/traverse/lib/context.js:138:19)
```

### PR DESCRIPTION
**Pull request by hsource**
## Motivation

Fixes #270. babel-traverse expects that it's passed an entire tree that spans to the top of the program. eslint does not guarantee that, which causes crashes when parsing some programs (see #270 for many examples).

## Fix

- Don't rely on the external library. Instead, just iterate through the node ourselves to get the full name
- **Side fix:** Add support so that even nested components inside of a `Text` or other allowed components are allowed. Nested text components can safely be used to add inline bold/color/other styling

## Testing

Added automated test based on repro case from #270: https://github.com/Intellicode/eslint-plugin-react-native/issues/270#issuecomment-897766305

### CODE REVIEW

**Review by eqlion — APPROVED** [review]

**Comment by JLHwung** [comment]
Babel's maintainer here.

https://github.com/Intellicode/eslint-plugin-react-native/blob/4b7149ea7019d288d6318dfabb05461f3134a975/lib/rules/no-raw-text.js#L52-L53

I am worried by the usage of `@babel/traverse` here:
- we are passing the ESLint scope to Babel's traverse.
- we are not respecting the ESLint AST shape, instead we treat the AST as if was parsed from Babel. This works from the sheer luck that Babel JSX AST is almost same as the one constructed by ESLint.

In #270, Babel is constructing a new scope when it visits a Function `() => {}` in the JSXOpeningElement `<foo bar={() => {}} />`. It _should_ work if the passed `scope` is created by Babel traverse, so that Babel can find all the way up to the program scope. But since we are passing an ESLint scope, it results to an obscure internal Babel error.

This PR looks good to me. If we want to be future-proof, we can get the `visitorKeys` of `JSXOpeningElement` from `context.getSourceCode().visitorKeys` and traverse accordingly.

**Comment by hsource** [comment]
@Intellicode I think this quick PR should resolve #270, which has seen a lot of activity. Can you help take a look?

**Comment by peterpme** [comment]
Merged into https://github.com/peterpme/eslint-plugin-react-native

**Comment by peterpme** [comment]
Merged into https://github.com/peterpme/eslint-plugin-react-native

**Review by Intellicode — APPROVED** [review]

**Comment by Intellicode** [comment]
Thanks for the fix @hsource, sorry for the late review, life got in the way

**Comment by peterpme** [comment]
Thank you @Intellicode!

I saw your README. I would be happy to take this over and maintain it. I work closely with React Native & the Expo team and would be honored to be passed the torch

**Pull request merged**
