### PR TITLE
Fixed no-raw-text rule for typescript

### PR DESCRIPTION
**Pull request by AleksandrZhukov**
- fixed rule for @typescript-eslint/parser
- added @typescript-eslint/parser as devDependency
- added .DS_Store to .gitignore

### CODE REVIEW

**Comment by AleksandrZhukov** [comment]
This PR fixes https://github.com/Intellicode/eslint-plugin-react-native/issues/208 and https://github.com/Intellicode/eslint-plugin-react-native/issues/210 issues

**Comment by donovanhiland** [comment]
🎉

**Comment by donovanhiland** [comment]
How long is typical for a review and merge of a PR like this?

**Comment by AleksandrZhukov** [comment]
I don't know, seems need to ask @Intellicode 🙏

**Comment by Intellicode** [comment]
Thanks for your PR, I'm not very familiar with the use case of typescript and eslint, can you explain a little bit about the dev dependencies @AleksandrZhukov?

**Comment by AleksandrZhukov** [comment]
@Intellicode I'm also not very familiar with typescript, but seems `typescript-eslint/parser` make little bit different AST from basic eslint parser. You can try to use another parser here https://astexplorer.net to check the difference. I've added `typescript` and `typescript-eslint/parser` dependencies to cover `no-raw-text` rule with tests.

**Comment by Intellicode** [comment]
@AleksandrZhukov alright, seems the other eslint react plugin has it as well, so lets go for it :)

**Pull request merged**
