### PR TITLE
Added no-raw-text rule

### PR DESCRIPTION
**Pull request by AleksandrZhukov**
- added new rule to prevent error of raw text, eg
  https://github.com/facebook/react-native/issues/15870
  https://github.com/react-community/react-native-maps/issues/1791
- added .idea folder to gitignore

### CODE REVIEW

**Comment by Intellicode** [comment]
Nice thanks! I'll have a look this weekend and create a new release

**Comment by draperunner** [comment]
Can you please release a new version with this change, @Intellicode? :)

**Comment by draperunner** [comment]
I installed the version from the latest git commit, and found a couple of issues: #203 #204 

Maybe @Intellicode and @AleksandrZhukov have some good ideas for how to solve them.

**Comment by AleksandrZhukov** [comment]
Will check this weekend

**Comment by Intellicode** [comment]
@draperunner its released!

**Pull request merged**
