### PR TITLE
flat config eslint 9.x.x working

### PR DESCRIPTION
**Pull request by MartinInAction**
Hola!
These changes makes implmentation with eslint 9.x.x working without any compat or hassle!

So if anyone wants to merge, we can move this package forward :)

### CODE REVIEW

**Comment by front-end-captain** [comment]
any progress?

**Comment by adminmne0001** [comment]
Any progress?

**Review by Intellicode — APPROVED** [review]

**Comment by Intellicode** [comment]
Thanks! Made a release

**Comment by kevinschaffter** [comment]
Thanks very much 🙏, do you mind updating the docs with suggested use? Just having trouble getting this to work with V9.

**Comment by kadikraman** [comment]
This is how to use it in flat config:

```js
const { defineConfig } = require("eslint/config");
const eslintPluginReactNative = require("eslint-plugin-react-native");

module.exports = defineConfig([
   // your other config
  {
    plugins: {
      "react-native": eslintPluginReactNative,
    },
    rules: {
      // enable the rules you want to use
      "react-native/no-unused-styles": "error",
    },
  },
]);

```

**Pull request merged**
