### PR TITLE
a more forgiving no-unused-styles

### LINKED ISSUE #15: no-unused-styles doesn't work with functions and vars
when I added the rule for `no-unused-styles` to my project I got many errors.
most of them were due to styles dynamically loaded from functions or vars.

consider the following use cases:

``` js
class MyView extends Component {

  static propTypes = {
    isActive: React.PropTypes.bool,
    type: React.PropTypes.oneOf(['typeA', 'typeB'])
  };

  get myActiveStyle() {
     return this.props.isActive ? style.active : {}
  }

 render() {
    var typeStyle = styles[this.props.type];
    return (
      <View style={[this.activeStyle, typeStyle]} / >
    );
  }

}

// All 3 styles will be marked as unused
const styles = StyleSheet.create({
   active: {...},
   typeA: {...},
   typeB: {...},
})
```

my current solution is to wrap the erroring code with:

``` js
/*eslint-disable react-native/no-unused-styles */
 const styles = StyleSheet.create({...});
/*eslint-enable react-native/no-unused-styles */
```

Thoughts?

### PR DESCRIPTION
**Pull request by kfiroo**
only check a refernce to the style exists in the code and not that it is in a style attribute. Fixes #15

### CODE REVIEW

**Comment by Intellicode** [comment]
Thanks for your PR! Could you also remove the dead code as result of this change? I can also do it if you like.

**Comment by kfiroo** [comment]
@Intellicode I'm on it :)

**Comment by FaridSafi** [comment]
+1

**Comment by Intellicode** [comment]
@kfiroo please let me know if there is anything I can help you with

**Comment by kfiroo** [comment]
@Intellicode So sorry, my computer decided to drink some vodka so I was "computerless" till now!
I will remove the dead code in the following week as I go over my backlog

**Comment by sibelius** [comment]
@Intellicode can we merge this please

**Comment by Intellicode** [comment]
@sibelius I guess I missed the additional commits, I'll do it soon!

**Pull request merged**
